import os

# DOCKER ENVIRONMENT VARIABLES
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_ADMIN = os.environ.get("TELEGRAM_ADMIN")
TELEGRAM_GROUP = os.environ.get("TELEGRAM_GROUP")
TELEGRAM_THREAD = os.environ.get("TELEGRAM_THREAD")
LANGUAGE = os.environ.get("LANGUAGE")

# CONSTANTS
ANONYMOUS_USER_ID = "1087968824"
DATA_PATH = "/app/data"
DEVICES_FILE = "devices"
DEVICES_FILE_PATH = f'{DATA_PATH}/{DEVICES_FILE}'